### ISSUE TITLE
Bootstrap issues with flux-operator

### ISSUE THREAD

**Issue by onedr0p** [ahinko/home-ops#4042]
Hi 👋🏼 

It looks like you might run into an issue bootstrapping your cluster because from I can tell the `FluxInstance` creates the Flux CRDs (like `GitRepository`, `HelmRelease` etc..) so your `kubectl` command [here](https://github.com/ahinko/home-ops/blob/84a1d7cf6f2896c62ea3acc32d4e00e3b8149030/.taskfiles/flux/taskfile.yaml#L24) would fail with something like "GitRepository CR not found". Feel free to let me know otherwise but I am pretty sure that is the case.

The way around this I was thinking to put the `instance.yaml` and `cluster.yaml` in separate directories and then update the taskfile to do

```yaml
- kubectl apply --server-side --kustomize {{.CLUSTER_DIR}}/flux/instance
- until kubectl wait fluxinstance --for=condition=Ready --timeout=10m --all --all-namespaces &>/dev/null; do sleep 5; done
- kubectl apply --server-side --kustomize {{.CLUSTER_DIR}}/flux/config
```

**Comment by ahinko** [comment]
Hi and thank you, I think you are absolutely right. To be honest, I haven't tested or had the need to bootstrap the cluster in quite a while so I've made some guesses when I changed to the Flux operator.
